In [1]:
import numpy as np
import pandas as pd

- ***creating a data frame***

In [2]:
data_dist = { # data dictionary
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df_dist = pd.DataFrame(data_dist)
df_dist # output -> table format with headers name & 0 based indexing

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [3]:
data_list = [
    ["John", 28, "New York", 65000],
    ["Anna", 34, "Paris", 70000],
    ["Peter", 29, "Berlin", 62000],
    ["Linda", 42, "London", 85000],
]

df_list = pd.DataFrame(data_list)
df_list # output -> table format with 0 based indexing and headers

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [4]:
headers = ["Name", "Age", "City", "Salary"]
df_list_with_col = pd.DataFrame(data_list, columns = headers)
df_list_with_col

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

- ***selection & indexing of columns***

In [5]:
df_dist

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [6]:
names = df_dist["Name"]
names # target the Name column

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [7]:
city = df_dist["City"]
city  # target the City column

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [8]:
name_with_city = df_dist[["Name", "City"]]
name_with_city # target the both columns ["Name", ,"City"]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

- ***creating a new columns***

In [9]:
data_dist["Designation"] = ["Doctor", "Eng.", "Doctor", "Eng."]
new_col = pd.DataFrame(data_dist)
new_col # add new column

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000        Eng.
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000        Eng.

- ***removing columns***

In [10]:
# new_col.drop("Designation", axis = 1) # funx don't affect the original data
# new_col.drop("Designation", axis = 1, inplace = True) # affect the original data
new_col = new_col.drop("Designation", axis = 1) # remove row in original data-> axis 1 for entire col & 0 for row
new_col

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

- ***selecting rows***

In [11]:
df_dist

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [12]:
first_row_data = df_dist.loc[0]
first_row_data

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [13]:
multiple_row_data = df_dist.loc[[0, 1]]
multiple_row_data

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [15]:
index_location_data = df_dist.iloc[3]
index_location_data

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

- ***selecting subsets of rows & columns***

In [16]:
df_dist

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [18]:
subset = df_dist.loc[[0, 1]][["City", "Salary"]] 
subset

       City  Salary
0  New York   65000
1     Paris   70000

In [20]:
subset2 = df_dist.loc[[2, 3]][["Name", "Age"]]
subset2

    Name  Age
2  Peter   29
3  Linda   42

- ***conditional selection***

In [21]:
df_dist

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
age_above_30 = df_dist[df_dist["Age"] > 30]
age_above_30

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [24]:
age_above_30_and_paris = df_dist[(df_dist["Age"] > 30) & (df_dist["City"] == 'Paris')]
age_above_30_and_paris

   Name  Age   City  Salary
1  Anna   34  Paris   70000