In [1]:
import numpy as np
import pandas as pd

- ***merging 2 dataframes***

In [2]:
employees = pd.DataFrame(
    {
        "employee_id" : [1, 2, 3, 4, 5],
        "name" : ["John", "Anna", "Peter", "Linda", "Bob"],
        "department" : ["HR", "IT", "Finance", "IT", "HR"],
    }
)

salaries = pd.DataFrame(
    {
        "employee_id" : [1, 2, 3, 6, 7],
        "salary" : [60000, 80000, 65000, 70000, 90000],
        "bonus" : [5000, 10000, 7000, 8000, 12000],
    }
)

In [3]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [4]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [6]:
merged_inner_df = pd.merge(employees, salaries) # common values
merged_inner_df

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [7]:
merged_inner_df = pd.merge(employees, salaries, how = 'outer')  # all values
merged_inner_df

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [8]:
merged_left_df = pd.merge(employees, salaries, how = 'left')  # merge on left basis
merged_left_df

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [9]:
merged_right_df = pd.merge(employees, salaries, how = 'right')  # merge on right basis
merged_right_df

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

- ***concatination of 2 dataframes***

In [10]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2"], 
        "B": ["B0", "B1", "B2"], 
        "C": ["C0", "C1", "C2"]
    }
)

df2 = pd.DataFrame(
    {
        "A": ["A3", "A4", "A5"], 
        "B": ["B3", "B4", "B5"], 
        "C": ["C3", "C4", "C5"]
    }
)

In [11]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [12]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
concat_col = pd.concat([df2, df1]) # combine df in column
concat_col

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [14]:
concat_row = pd.concat([df2, df1], axis = 1)  # combine df in row
concat_row

    A   B   C   A   B   C
0  A3  B3  C3  A0  B0  C0
1  A4  B4  C4  A1  B1  C1
2  A5  B5  C5  A2  B2  C2

- ***joining of 2 dataframes***

In [20]:
join_df1 = pd.DataFrame(
    {
        "name": ["Alice", "Bob", "Charlie"]
    }, 
    index=[1, 2, 3]
)

join_df2 = pd.DataFrame(
    {
        "score": [85, 90, 75]
    },
    index=[2, 3, 4]
)

In [21]:
join_df1

      name
1    Alice
2      Bob
3  Charlie

In [22]:
join_df2

   score
2     85
3     90
4     75

In [24]:
join_df1.join(join_df2) # join the df based on common index

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [25]:
join_df1.join(join_df2, how = 'outer')  # join the df based on all index

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0